---
deprecations:
  - |
    The following octavia::worker parameters are deprecated and have been
    moved to octavia::controller class. When you start using octavia::controller
    make sure it's defined before octavia::worker.

      * amp_flavor_id
      * amp_image_tag
      * amp_secgroup_list
      * amp_boot_network_list
      * loadbalancer_topology
      * amphora_driver
      * compute_driver
      * network_driver
      * amp_ssh_key_name
      * enable_ssh_access
      * timeout_member_connect
      * timeout_member_data
      * timeout_tcp_inspect
fixes:
  - |
    There are a couple of configuration options that need to be set not only
    for the worker but also for other Octavia services. For example, on a
    composable node deployment where the API runs on a separate node than
    the rest of the Octavia services, the network driver was not being set
    (hence defaulting to noop driver) while for the worker the driver was
    allowed_address_pairs_driver. Another example is the database that was only
    being set for the API service. Such configuration misalignment and
    omissions lead to operate Octavia services and its resources. 
upgrade:
  - |
    If you want to use the new octavia::controller class you must define it
    before the octavia::worker class.
